"""SQLAlchemy table registrations for the agent domain."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    UniqueConstraint,
)

from ._base import _owned_columns, metadata


Table(
    "agent_provider_profiles",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("provider_id", String(100), nullable=False),
    Column("adapter_version", String(100), nullable=False),
    Column("model_snapshot", String(100), nullable=False),
    Column("settings_sha256", String(64), nullable=False),
    Column("response_storage_enabled", Boolean, nullable=False),
    Column("background_enabled", Boolean, nullable=False),
    Column("provider_tracing_enabled", Boolean, nullable=False),
    Column("profile_state", String(32), nullable=False),
    *_owned_columns(),
    UniqueConstraint(
        "tenant_id", "provider_id", "adapter_version", "model_snapshot", name="uq_agent_provider_tenant_version"
    ),
)

Table(
    "agent_projected_tools",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("tool_fqn", String(200), nullable=False),
    Column("projection_revision", Integer, nullable=False),
    Column("source_capability_id", String(100), nullable=False),
    Column("source_capability_revision", Integer, nullable=False),
    Column("source_capability_sha256", String(64), nullable=False),
    Column("adapter_id", String(100), nullable=False),
    Column("adapter_version", String(100), nullable=False),
    Column("input_schema_sha256", String(64), nullable=False),
    Column("result_schema_sha256", String(64), nullable=False),
    Column("description_sha256", String(64), nullable=False),
    Column("network_class", String(32), nullable=False),
    Column("access_class", String(32), nullable=False),
    Column("approval_tier", String(32), nullable=False),
    Column("budget_policy", JSON, nullable=False),
    Column("unsupported_features", JSON, nullable=False),
    Column("tool_state", String(32), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "tool_fqn", "projection_revision", name="uq_agent_tool_tenant_revision"),
)

Table(
    "agent_runs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_id", String(100), nullable=False),
    Column("provider_record_id", String(64), ForeignKey("agent_provider_profiles.id"), nullable=False),
    Column("campaign_id", String(100), nullable=False),
    Column("operator_id", String(64), nullable=False),
    Column("trusted_context_sha256", String(64), nullable=False),
    Column("registry_sha256", String(64), nullable=False),
    Column("run_state", String(32), nullable=False),
    Column("cancel_requested", Boolean, nullable=False),
    Column("failure_code", String(100)),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "run_id", name="uq_agent_run_tenant_id"),
)

Table(
    "agent_steps",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("agent_runs.id"), nullable=False),
    Column("step_id", String(100), nullable=False),
    Column("step_order", Integer, nullable=False),
    Column("step_kind", String(32), nullable=False),
    Column("request_sha256", String(64), nullable=False),
    Column("response_sha256", String(64)),
    Column("trust_class", String(32), nullable=False),
    Column("step_state", String(32), nullable=False),
    Column("error_code", String(100)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "run_record_id", "step_order", name="uq_agent_step_tenant_order"),
)

Table(
    "agent_proposals",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("agent_runs.id"), nullable=False),
    Column("tool_record_id", String(64), ForeignKey("agent_projected_tools.id"), nullable=False),
    Column("proposal_id", String(100), nullable=False),
    Column("call_id", String(100), nullable=False),
    Column("proposal_sha256", String(64), nullable=False),
    Column("argument_sha256", String(64), nullable=False),
    Column("target_sha256", String(64), nullable=False),
    Column("side_effect_classes", JSON, nullable=False),
    Column("roe_version_id", String(100), nullable=False),
    Column("policy_revision", String(100), nullable=False),
    Column("policy_decision_id", String(100), nullable=False),
    Column("proposal_state", String(32), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "proposal_id", name="uq_agent_proposal_tenant_id"),
)

Table(
    "agent_approvals",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("proposal_record_id", String(64), ForeignKey("agent_proposals.id"), nullable=False),
    Column("approval_id", String(100), nullable=False),
    Column("proposal_sha256", String(64), nullable=False),
    Column("approved_by", String(64), nullable=False),
    Column("nonce_sha256", String(64), nullable=False),
    Column("approval_state", String(32), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("consumed_at", DateTime(timezone=True)),
    Column("revoked_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "approval_id", name="uq_agent_approval_tenant_id"),
    UniqueConstraint("tenant_id", "nonce_sha256", name="uq_agent_approval_tenant_nonce"),
)

Table(
    "agent_budget_ledgers",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("agent_runs.id"), nullable=False),
    Column("ledger_id", String(100), nullable=False),
    Column("budget_sha256", String(64), nullable=False),
    Column("turn_count", Integer, nullable=False),
    Column("tool_call_count", Integer, nullable=False),
    Column("input_token_count", Integer, nullable=False),
    Column("result_token_count", Integer, nullable=False),
    Column("cost_microunits", BigInteger, nullable=False),
    Column("result_bytes", BigInteger, nullable=False),
    Column("elapsed_millis", BigInteger, nullable=False),
    Column("ledger_state", String(32), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "ledger_id", name="uq_agent_budget_tenant_id"),
)

Table(
    "agent_working_memory",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("memory_id", String(100), nullable=False),
    Column("run_record_id", String(64), ForeignKey("agent_runs.id"), nullable=False),
    Column("ciphertext_sha256", String(64), nullable=False),
    Column("key_reference_id", String(100), nullable=False),
    Column("trust_label", String(32), nullable=False),
    Column("plaintext_bytes", Integer, nullable=False),
    Column("memory_state", String(32), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("deleted_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "memory_id", name="uq_agent_memory_tenant_id"),
)

Table(
    "agent_reviewed_facts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("fact_id", String(100), nullable=False),
    Column("candidate_sha256", String(64), nullable=False),
    Column("provenance_sha256", String(64), nullable=False),
    Column("proposed_by", String(64), nullable=False),
    Column("reviewed_by", String(64), nullable=False),
    Column("trust_label", String(32), nullable=False),
    Column("fact_state", String(32), nullable=False),
    Column("reviewed_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "fact_id", name="uq_agent_fact_tenant_id"),
)

Table(
    "agent_trace_envelopes",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("trace_id", String(100), nullable=False),
    Column("span_id", String(100), nullable=False),
    Column("parent_span_id", String(100)),
    Column("run_record_id", String(64), ForeignKey("agent_runs.id"), nullable=False),
    Column("event_type", String(100), nullable=False),
    Column("trace_state", String(32), nullable=False),
    Column("input_sha256", String(64), nullable=False),
    Column("output_sha256", String(64), nullable=False),
    Column("policy_decision_id", String(100)),
    Column("approval_id", String(100)),
    Column("evidence_id", String(100)),
    Column("error_code", String(100)),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "trace_id", "span_id", name="uq_agent_trace_tenant_span"),
)

Table(
    "agent_qualification_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("qualification_id", String(100), nullable=False),
    Column("registry_sha256", String(64), nullable=False),
    Column("provider_id", String(100), nullable=False),
    Column("provider_settings_sha256", String(64), nullable=False),
    Column("scenario_sha256", String(64), nullable=False),
    Column("adversarial_case_count", Integer, nullable=False),
    Column("denied_case_count", Integer, nullable=False),
    Column("external_contact_count", Integer, nullable=False),
    Column("direct_dispatch_count", Integer, nullable=False),
    Column("sensitive_retention_count", Integer, nullable=False),
    Column("qualification_state", String(32), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "qualification_id", name="uq_agent_qualification_tenant_id"),
)
