"""SQLAlchemy table registrations for the campaign loop domain."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    UniqueConstraint,
)

from ._base import _owned_columns, metadata


Table(
    "campaign_strategy_revisions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("strategy_revision_id", String(100), nullable=False),
    Column("campaign_id", String(64), ForeignKey("campaigns.id"), nullable=False),
    Column("predecessor_revision_id", String(100)),
    Column("plan_revision", Integer, nullable=False),
    Column("replan_count", Integer, nullable=False),
    Column("context_schema", String(100), nullable=False),
    Column("context_sha256", String(64), nullable=False),
    Column("context_payload", JSON, nullable=False),
    Column("decision_schema", String(100), nullable=False),
    Column("decision_sha256", String(64), nullable=False),
    Column("decision_payload", JSON, nullable=False),
    Column("plan_sha256", String(64), nullable=False),
    Column("plan_payload", JSON, nullable=False),
    Column("proposal_ceiling_sha256", String(64), nullable=False),
    Column("approval_receipt_id", String(100), nullable=False),
    Column("approval_receipt_revision", Integer, nullable=False),
    Column("approval_receipt_sha256", String(64), nullable=False),
    Column("envelope_core_sha256", String(64), nullable=False),
    Column("envelope_sha256", String(64), nullable=False),
    Column("created_by_user_id", String(64), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "strategy_revision_id", name="uq_campaign_strategy_tenant_revision"),
    UniqueConstraint("tenant_id", "campaign_id", "plan_revision", name="uq_campaign_strategy_tenant_plan_revision"),
    CheckConstraint("plan_revision BETWEEN 1 AND 2", name="campaign_strategy_plan_revision_bounded"),
    CheckConstraint("replan_count BETWEEN 0 AND 1", name="campaign_strategy_replan_count_bounded"),
)

Table(
    "campaign_effects",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("effect_id", String(100), nullable=False),
    Column("campaign_id", String(64), ForeignKey("campaigns.id"), nullable=False),
    Column("strategy_revision_id", String(64), ForeignKey("campaign_strategy_revisions.id"), nullable=False),
    Column("node_id", String(100), nullable=False),
    Column("invocation_id", String(100), nullable=False),
    Column("effect_intent_sha256", String(64), nullable=False),
    Column("effect_intent_payload", JSON, nullable=False),
    Column("envelope_sha256", String(64), nullable=False),
    Column("effect_state", String(32), nullable=False),
    Column("claim_owner", String(100)),
    Column("claim_expires_at", DateTime(timezone=True)),
    Column("claim_version", Integer, nullable=False, default=0),
    Column("dispatch_attempt", Integer, nullable=False, default=0),
    Column("dispatch_generation", Integer, nullable=False, default=0),
    Column("runner_id", String(100)),
    Column("workload_identity", String(300)),
    Column("request_sha256", String(64)),
    Column("effect_receipt_sha256", String(64)),
    Column("effect_receipt_payload", JSON),
    Column("external_status", String(100)),
    Column("external_receipt_id", String(100)),
    Column("evidence_ids", JSON, nullable=False, default=list),
    Column("cleanup_receipt_id", String(100)),
    Column("reconciliation_state", String(32), nullable=False, default="none"),
    Column("reconciliation_evidence_ids", JSON, nullable=False, default=list),
    Column("redispatch_permitted", Boolean, nullable=False, default=False),
    Column("failure_code", String(100)),
    Column("next_retry_at", DateTime(timezone=True)),
    Column("outbox_sequence", BigInteger, nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "effect_id", name="uq_campaign_effect_tenant_effect"),
    UniqueConstraint(
        "tenant_id", "campaign_id", "strategy_revision_id", "node_id", name="uq_campaign_effect_stable_node"
    ),
    CheckConstraint("claim_version BETWEEN 0 AND 2147483647", name="campaign_effect_claim_version_bounded"),
    CheckConstraint("dispatch_attempt BETWEEN 0 AND 2", name="campaign_effect_dispatch_attempt_bounded"),
    CheckConstraint("dispatch_generation BETWEEN 0 AND 2147483647", name="campaign_effect_dispatch_generation_bounded"),
    CheckConstraint("outbox_sequence BETWEEN 1 AND 2147483647", name="campaign_effect_outbox_sequence_bounded"),
    CheckConstraint(
        "effect_state IN ('reserved','claimed','dispatching','reconciliation_required','not_applied','confirmed','compensated','manual_review_required','failed')",
        name="campaign_effect_state_closed",
    ),
    CheckConstraint(
        "reconciliation_state IN ('none','reconciliation_required','confirmed','not_applied','compensated','manual_review_required')",
        name="campaign_effect_reconciliation_state_closed",
    ),
)
