"""SQLAlchemy table registrations for the lab domain."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    UniqueConstraint,
)

from ._base import _owned_columns, metadata


Table(
    "lab_bundles",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("bundle_id", String(100), nullable=False),
    Column("bundle_revision", Integer, nullable=False),
    Column("fixture_digest", String(71), nullable=False),
    Column("seed_manifest_sha256", String(64), nullable=False),
    Column("network_id", String(100), nullable=False),
    Column("manifest", JSON, nullable=False),
    Column("bundle_state", String(32), nullable=False),
    Column("activated_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "bundle_id", "bundle_revision", name="uq_lab_bundles_tenant_revision"),
)

Table(
    "lab_target_attestations",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("bundle_record_id", String(64), ForeignKey("lab_bundles.id"), nullable=False),
    Column("attestation_id", String(100), nullable=False),
    Column("target_id", String(100), nullable=False),
    Column("fixture_kind", String(32), nullable=False),
    Column("endpoint", String(200), nullable=False),
    Column("network_id", String(100), nullable=False),
    Column("allowed_test_classes", JSON, nullable=False),
    Column("expected_finding_manifest_sha256", String(64), nullable=False),
    Column("attestation_sha256", String(64), nullable=False),
    Column("non_production", Boolean, nullable=False),
    Column("attestation_state", String(32), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "attestation_id", name="uq_lab_attestations_tenant_attestation"),
    UniqueConstraint("tenant_id", "target_id", "attestation_sha256", name="uq_lab_attestations_tenant_target_hash"),
)

Table(
    "lab_target_leases",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("attestation_record_id", String(64), ForeignKey("lab_target_attestations.id"), nullable=False),
    Column("lease_id", String(100), nullable=False),
    Column("target_id", String(100), nullable=False),
    Column("runner_id", String(100), nullable=False),
    Column("test_class", String(32), nullable=False),
    Column("endpoint", String(200), nullable=False),
    Column("attestation_sha256", String(64), nullable=False),
    Column("policy_reference", String(200), nullable=False),
    Column("roe_version_id", String(64), nullable=False),
    Column("lease_state", String(32), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "lease_id", name="uq_lab_target_leases_tenant_lease"),
)

Table(
    "golden_scenario_runs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("bundle_record_id", String(64), ForeignKey("lab_bundles.id"), nullable=False),
    Column("run_id", String(100), nullable=False),
    Column("scenario_id", String(100), nullable=False),
    Column("scenario_state", String(32), nullable=False),
    Column("current_step", Integer, nullable=False),
    Column("last_action_id", String(100)),
    Column("reason_code", String(100), nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    *_owned_columns(),
    CheckConstraint("current_step >= 0", name="ck_golden_scenario_step_nonnegative"),
    UniqueConstraint("tenant_id", "run_id", "scenario_id", name="uq_golden_scenario_runs_tenant_run_scenario"),
)

Table(
    "golden_scenario_steps",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("scenario_run_record_id", String(64), ForeignKey("golden_scenario_runs.id"), nullable=False),
    Column("step_id", String(100), nullable=False),
    Column("action_id", String(100), nullable=False),
    Column("step_name", String(100), nullable=False),
    Column("step_state", String(32), nullable=False),
    Column("request_sha256", String(64), nullable=False),
    Column("receipt_sha256", String(64), nullable=False),
    Column("request_count", Integer, nullable=False),
    Column("contact_count", Integer, nullable=False),
    Column("reason_code", String(100), nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    CheckConstraint("request_count >= 0 AND contact_count >= 0", name="ck_golden_step_counts_nonnegative"),
    UniqueConstraint("tenant_id", "action_id", name="uq_golden_scenario_steps_tenant_action"),
)

Table(
    "golden_finding_expectations",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("bundle_record_id", String(64), ForeignKey("lab_bundles.id"), nullable=False),
    Column("expectation_id", String(100), nullable=False),
    Column("fixture_kind", String(32), nullable=False),
    Column("tool", String(100), nullable=False),
    Column("rule_id", String(200), nullable=False),
    Column("tool_version", String(100), nullable=False),
    Column("database_version", String(100), nullable=False),
    Column("title", String(500), nullable=False),
    Column("severity", String(32), nullable=False),
    Column("confidence", String(32), nullable=False),
    Column("resource_id", String(100), nullable=False),
    Column("evidence_class", String(32), nullable=False),
    Column("fingerprint", String(64), nullable=False),
    Column("expectation_sha256", String(64), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "expectation_id", name="uq_golden_findings_tenant_expectation"),
    UniqueConstraint(
        "tenant_id", "bundle_record_id", "fingerprint", name="uq_golden_findings_tenant_bundle_fingerprint"
    ),
)

Table(
    "qualification_measurements",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("scenario_run_record_id", String(64), ForeignKey("golden_scenario_runs.id")),
    Column("measurement_id", String(100), nullable=False),
    Column("metric_id", String(100), nullable=False),
    Column("comparison", String(8), nullable=False),
    Column("observed_millionths", BigInteger, nullable=False),
    Column("threshold_millionths", BigInteger, nullable=False),
    Column("unit", String(64), nullable=False),
    Column("sample_count", Integer, nullable=False),
    Column("p95_millionths", BigInteger),
    Column("result_state", String(32), nullable=False),
    Column("artifact_sha256", String(64), nullable=False),
    Column("measured_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    CheckConstraint("sample_count > 0", name="ck_qualification_measurement_samples_positive"),
    UniqueConstraint("tenant_id", "measurement_id", name="uq_qualification_measurements_tenant_measurement"),
)

Table(
    "lab_backup_restore_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("scenario_run_record_id", String(64), ForeignKey("golden_scenario_runs.id"), nullable=False),
    Column("receipt_id", String(100), nullable=False),
    Column("source_inventory_sha256", String(64), nullable=False),
    Column("restored_inventory_sha256", String(64), nullable=False),
    Column("source_schema_revision", String(32), nullable=False),
    Column("restored_schema_revision", String(32), nullable=False),
    Column("source_row_count", BigInteger, nullable=False),
    Column("restored_row_count", BigInteger, nullable=False),
    Column("source_object_count", BigInteger, nullable=False),
    Column("restored_object_count", BigInteger, nullable=False),
    Column("restore_state", String(32), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "receipt_id", name="uq_lab_restore_receipts_tenant_receipt"),
)

Table(
    "lab_teardown_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("scenario_run_record_id", String(64), ForeignKey("golden_scenario_runs.id"), nullable=False),
    Column("receipt_id", String(100), nullable=False),
    Column("container_count", Integer, nullable=False),
    Column("network_count", Integer, nullable=False),
    Column("volume_count", Integer, nullable=False),
    Column("residual_resource_count", Integer, nullable=False),
    Column("teardown_complete", Boolean, nullable=False),
    Column("inventory_sha256", String(64), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    CheckConstraint(
        "container_count >= 0 AND network_count >= 0 AND volume_count >= 0 AND residual_resource_count >= 0",
        name="ck_lab_teardown_counts_nonnegative",
    ),
    UniqueConstraint("tenant_id", "receipt_id", name="uq_lab_teardown_receipts_tenant_receipt"),
)
