"""SQLAlchemy table registrations for the runner domain."""

from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    UniqueConstraint,
)

from ._base import _owned_columns, metadata


Table(
    "runner_classes",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("class_id", String(100), nullable=False),
    Column("class_revision", Integer, nullable=False),
    Column("environment", String(64), nullable=False),
    Column("network_plane", String(64), nullable=False),
    Column("isolation_tier", String(32), nullable=False),
    Column("runtime_name", String(32), nullable=False),
    Column("sandbox_profile_id", String(100), nullable=False),
    Column("policy_revision", String(100), nullable=False),
    Column("resource_limits", JSON, nullable=False),
    Column("credential_classes", JSON, nullable=False),
    Column("evidence_schemas", JSON, nullable=False),
    Column("class_status", String(32), nullable=False),
    Column("author_user_id", String(64), nullable=False),
    Column("reviewer_user_id", String(64), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "class_id", "class_revision", name="uq_runner_classes_tenant_class_revision"),
)

Table(
    "runner_registrations",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("runner_id", String(100), nullable=False),
    Column("runner_class_record_id", String(64), ForeignKey("runner_classes.id"), nullable=False),
    Column("environment", String(64), nullable=False),
    Column("network_plane", String(64), nullable=False),
    Column("spiffe_id", String(300), nullable=False),
    Column("certificate_fingerprint", String(64), nullable=False),
    Column("certificate_serial", String(100), nullable=False),
    Column("adapter_allowlist", JSON, nullable=False),
    Column("image_allowlist", JSON, nullable=False),
    Column("required_policy_revision", String(100), nullable=False),
    Column("generation", Integer, nullable=False),
    Column("attestation_sha256", String(64), nullable=False),
    Column("registration_state", String(32), nullable=False),
    Column("registered_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True)),
    Column("last_seen_at", DateTime(timezone=True)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "runner_id", "generation", name="uq_runner_registrations_tenant_runner_generation"),
)

Table(
    "runner_identities",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("registration_id", String(64), ForeignKey("runner_registrations.id"), nullable=False),
    Column("spiffe_id", String(300), nullable=False),
    Column("certificate_fingerprint", String(64), nullable=False),
    Column("certificate_serial", String(100), nullable=False),
    Column("not_before", DateTime(timezone=True), nullable=False),
    Column("not_after", DateTime(timezone=True), nullable=False),
    Column("identity_state", String(32), nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "certificate_fingerprint", name="uq_runner_identities_tenant_fingerprint"),
)

Table(
    "execution_capability_manifests",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("capability_id", String(100), nullable=False),
    Column("capability_revision", Integer, nullable=False),
    Column("adapter_id", String(100), nullable=False),
    Column("adapter_version", String(100), nullable=False),
    Column("image_digest", String(71), nullable=False),
    Column("input_schema_id", String(100), nullable=False),
    Column("supported_modes", JSON, nullable=False),
    Column("phases", JSON, nullable=False),
    Column("sandbox_profile_id", String(100), nullable=False),
    Column("network_mode", String(32), nullable=False),
    Column("credential_class", String(32), nullable=False),
    Column("evidence_schema", JSON, nullable=False),
    Column("unsupported_features", JSON, nullable=False),
    Column("resource_limits", JSON, nullable=False),
    Column("artifact_receipt_id", String(64), nullable=False),
    Column("manifest_sha256", String(64), nullable=False),
    Column("reviewed_by_user_id", String(64), nullable=False),
    Column("capability_status", String(32), nullable=False),
    *_owned_columns(),
    UniqueConstraint(
        "tenant_id", "capability_id", "capability_revision", name="uq_execution_capabilities_tenant_capability_revision"
    ),
)

Table(
    "artifact_verification_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("receipt_id", String(100), nullable=False),
    Column("image_digest", String(71), nullable=False),
    Column("signature_verified", Boolean, nullable=False),
    Column("signature_sha256", String(64), nullable=False),
    Column("signer_identity", String(200), nullable=False),
    Column("provenance_sha256", String(64), nullable=False),
    Column("sbom_sha256", String(64), nullable=False),
    Column("vulnerability_review", String(64), nullable=False),
    Column("verifier", String(100), nullable=False),
    Column("verified_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "image_digest", name="uq_artifact_verification_tenant_image_digest"),
)

Table(
    "runner_job_manifests",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("manifest_id", String(100), nullable=False),
    Column("job_id", String(64), ForeignKey("jobs.id"), nullable=False),
    Column("runner_registration_id", String(64), ForeignKey("runner_registrations.id"), nullable=False),
    Column("idempotency_key", String(200), nullable=False),
    Column("request_hash", String(64), nullable=False),
    Column("manifest_document", JSON, nullable=False),
    Column("manifest_sha256", String(64), nullable=False),
    Column("signature_sha256", String(64), nullable=False),
    Column("signing_key_id", String(100), nullable=False),
    Column("capability_id", String(100), nullable=False),
    Column("capability_revision", Integer, nullable=False),
    Column("capability_sha256", String(64), nullable=False),
    Column("image_digest", String(71), nullable=False),
    Column("artifact_receipt_id", String(64), nullable=False),
    Column("policy_revision", String(100), nullable=False),
    Column("policy_decision_id", String(100), nullable=False),
    Column("nonce_hash", String(64), nullable=False),
    Column("manifest_state", String(32), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "job_id", "idempotency_key", name="uq_runner_manifests_tenant_job_request"),
)

Table(
    "runner_pull_leases",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("manifest_id", String(64), ForeignKey("runner_job_manifests.id"), nullable=False),
    Column("runner_registration_id", String(64), ForeignKey("runner_registrations.id"), nullable=False),
    Column("claim_id", String(100), nullable=False),
    Column("lease_token_hash", String(64), nullable=False),
    Column("runner_generation", Integer, nullable=False),
    Column("manifest_sha256", String(64), nullable=False),
    Column("lease_state", String(32), nullable=False),
    Column("claimed_at", DateTime(timezone=True), nullable=False),
    Column("last_heartbeat_at", DateTime(timezone=True)),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("finalized_at", DateTime(timezone=True)),
    Column("failure_code", String(100)),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "manifest_id", name="uq_runner_pull_leases_tenant_manifest"),
)

Table(
    "runner_lifecycle_events",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("lease_id", String(64), ForeignKey("runner_pull_leases.id"), nullable=False),
    Column("event_id", String(100), nullable=False),
    Column("phase", String(32), nullable=False),
    Column("event_sha256", String(64), nullable=False),
    Column("phase_state", String(32), nullable=False),
    Column("reason_code", String(100)),
    Column("metadata", JSON, nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "event_id", name="uq_runner_lifecycle_events_tenant_event"),
)

Table(
    "runner_execution_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("lease_id", String(64), ForeignKey("runner_pull_leases.id"), nullable=False),
    Column("evidence_artifact_id", String(64), ForeignKey("evidence_artifacts.id")),
    Column("execution_id", String(100), nullable=False),
    Column("outcome", String(32), nullable=False),
    Column("final_phase", String(32), nullable=False),
    Column("policy_decision_id", String(100), nullable=False),
    Column("evidence_sha256", String(64)),
    Column("cleanup_completed", Boolean, nullable=False),
    Column("residual_risk", String(100)),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "execution_id", name="uq_runner_execution_receipts_tenant_execution"),
)
