"""SQLAlchemy table registrations for the zap domain."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    UniqueConstraint,
)

from ._base import _owned_columns, metadata


Table(
    "zap_profile_revisions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("profile_id", String(100), nullable=False),
    Column("profile_revision", Integer, nullable=False),
    Column("image_version", String(32), nullable=False),
    Column("image_digest", String(71), nullable=False),
    Column("addon_inventory_sha256", String(64), nullable=False),
    Column("profile_sha256", String(64), nullable=False),
    Column("risk_class", String(32), nullable=False),
    Column("passive_rule_ids", JSON, nullable=False),
    Column("active_rule_ids", JSON, nullable=False),
    Column("request_limit", Integer, nullable=False),
    Column("request_rate_per_second", Integer, nullable=False),
    Column("concurrency_limit", Integer, nullable=False),
    Column("timeout_seconds", Integer, nullable=False),
    Column("response_bytes_limit", BigInteger, nullable=False),
    Column("profile_state", String(32), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "profile_id", "profile_revision", name="uq_zap_profile_tenant_revision"),
)

Table(
    "zap_target_attestations",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("attestation_id", String(100), nullable=False),
    Column("target_id", String(100), nullable=False),
    Column("target_source_sha256", String(64), nullable=False),
    Column("target_image_id", String(71), nullable=False),
    Column("network_id", String(100), nullable=False),
    Column("container_name", String(100), nullable=False),
    Column("address_sha256", String(64), nullable=False),
    Column("endpoint", String(200), nullable=False),
    Column("allowed_paths", JSON, nullable=False),
    Column("attestation_sha256", String(64), nullable=False),
    Column("non_production", Boolean, nullable=False),
    Column("attestation_state", String(32), nullable=False),
    Column("issued_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "attestation_id", name="uq_zap_target_attestation_tenant_id"),
    UniqueConstraint("tenant_id", "target_id", "attestation_sha256", name="uq_zap_target_attestation_tenant_hash"),
)

Table(
    "zap_compiled_plans",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("profile_record_id", String(64), ForeignKey("zap_profile_revisions.id"), nullable=False),
    Column("plan_id", String(100), nullable=False),
    Column("target_id", String(100), nullable=False),
    Column("target_attestation_sha256", String(64), nullable=False),
    Column("policy_decision_id", String(100), nullable=False),
    Column("roe_version_id", String(64), nullable=False),
    Column("plan_sha256", String(64), nullable=False),
    Column("scope_sha256", String(64), nullable=False),
    Column("compiled_plan", JSON, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "plan_id", name="uq_zap_plan_tenant_plan"),
)

Table(
    "zap_runs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("plan_record_id", String(64), ForeignKey("zap_compiled_plans.id"), nullable=False),
    Column("run_id", String(100), nullable=False),
    Column("job_id", String(100), nullable=False),
    Column("runner_id", String(100), nullable=False),
    Column("run_state", String(32), nullable=False),
    Column("current_step", Integer, nullable=False),
    Column("progress_percent", Integer, nullable=False),
    Column("passive_queue_size", Integer, nullable=False),
    Column("reason_code", String(100), nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    *_owned_columns(),
    CheckConstraint("progress_percent >= 0 AND progress_percent <= 100", name="ck_zap_progress_percent"),
    CheckConstraint("passive_queue_size >= 0", name="ck_zap_passive_queue_nonnegative"),
    UniqueConstraint("tenant_id", "run_id", name="uq_zap_run_tenant_run"),
)

Table(
    "zap_run_steps",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("zap_runs.id"), nullable=False),
    Column("step_id", String(100), nullable=False),
    Column("step_type", String(32), nullable=False),
    Column("step_state", String(32), nullable=False),
    Column("progress_percent", Integer, nullable=False),
    Column("request_count", Integer, nullable=False),
    Column("response_bytes", BigInteger, nullable=False),
    Column("receipt_sha256", String(64), nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    CheckConstraint("request_count >= 0 AND response_bytes >= 0", name="ck_zap_step_quota_nonnegative"),
    UniqueConstraint("tenant_id", "run_record_id", "step_id", name="uq_zap_step_tenant_run_step"),
)

Table(
    "zap_gateway_decisions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("zap_runs.id"), nullable=False),
    Column("decision_id", String(100), nullable=False),
    Column("method", String(16), nullable=False),
    Column("path_sha256", String(64), nullable=False),
    Column("destination_sha256", String(64), nullable=False),
    Column("allowed", Boolean, nullable=False),
    Column("reason_code", String(100), nullable=False),
    Column("request_count", Integer, nullable=False),
    Column("response_bytes", BigInteger, nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "decision_id", name="uq_zap_gateway_tenant_decision"),
)

Table(
    "zap_normalized_alerts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("zap_runs.id"), nullable=False),
    Column("alert_id", String(100), nullable=False),
    Column("rule_id", String(32), nullable=False),
    Column("title", String(200), nullable=False),
    Column("severity", String(32), nullable=False),
    Column("confidence", String(32), nullable=False),
    Column("affected_resource", String(200), nullable=False),
    Column("fingerprint", String(64), nullable=False),
    Column("evidence_instance_id", String(100), nullable=False),
    Column("source_sha256", String(64), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "run_record_id", "fingerprint", name="uq_zap_alert_tenant_run_fingerprint"),
)

Table(
    "zap_cancellation_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("zap_runs.id"), nullable=False),
    Column("receipt_id", String(100), nullable=False),
    Column("native_stop_attempted", Boolean, nullable=False),
    Column("native_stop_acknowledged", Boolean, nullable=False),
    Column("lease_revoked", Boolean, nullable=False),
    Column("evidence_finalized", Boolean, nullable=False),
    Column("forced_termination", Boolean, nullable=False),
    Column("reason_code", String(100), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    UniqueConstraint("tenant_id", "receipt_id", name="uq_zap_cancel_tenant_receipt"),
)

Table(
    "zap_cleanup_receipts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("run_record_id", String(64), ForeignKey("zap_runs.id"), nullable=False),
    Column("receipt_id", String(100), nullable=False),
    Column("container_count", Integer, nullable=False),
    Column("network_count", Integer, nullable=False),
    Column("home_count", Integer, nullable=False),
    Column("key_count", Integer, nullable=False),
    Column("credential_count", Integer, nullable=False),
    Column("residual_resource_count", Integer, nullable=False),
    Column("cleanup_complete", Boolean, nullable=False),
    Column("inventory_sha256", String(64), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=False),
    *_owned_columns(),
    CheckConstraint(
        "container_count >= 0 AND network_count >= 0 AND home_count >= 0 AND key_count >= 0 AND credential_count >= 0 AND residual_resource_count >= 0",
        name="ck_zap_cleanup_counts_nonnegative",
    ),
    UniqueConstraint("tenant_id", "receipt_id", name="uq_zap_cleanup_tenant_receipt"),
)
