"""compat_110 zero-untrusted-execution artifact assessment pipelines."""

from alembic import op
import sqlalchemy as sa


revision = "0017_r110_artifact"
down_revision = "0016_r109_identity"
branch_labels = None
depends_on = None


TABLES = (
    "artifact_adapter_artifacts", "artifact_pipeline_profiles", "artifact_rule_bundles", "artifact_database_snapshots",
    "artifact_bindings", "artifact_analysis_plans", "artifact_analysis_runs", "artifact_manifest_entries",
    "artifact_components", "artifact_license_observations", "artifact_vulnerability_observations", "artifact_vex_annotations",
    "artifact_credential_findings", "artifact_static_findings", "artifact_mobile_observations", "artifact_cleanup_receipts",
)


def upgrade() -> None:
    _create("artifact_adapter_artifacts", sa.Column("adapter_id", sa.String(100), nullable=False), sa.Column("artifact_sha256", sa.String(64), nullable=False), sa.Column("execution_enabled", sa.Boolean(), nullable=False), sa.Column("production_qualified", sa.Boolean(), nullable=False), sa.Column("legal_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "adapter_id", "artifact_sha256", name="uq_artifact_adapter_tenant_digest"))
    _create("artifact_pipeline_profiles", sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("artifact_kind", sa.String(32), nullable=False), sa.Column("profile_sha256", sa.String(64), nullable=False), sa.Column("stages", sa.JSON(), nullable=False), sa.Column("limits", sa.JSON(), nullable=False), sa.Column("zero_execution", sa.Boolean(), nullable=False), sa.Column("profile_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "profile_id", "profile_sha256", name="uq_artifact_profile_tenant_digest"))
    _create("artifact_rule_bundles", sa.Column("bundle_id", sa.String(100), nullable=False), sa.Column("bundle_kind", sa.String(32), nullable=False), sa.Column("bundle_version", sa.String(64), nullable=False), sa.Column("bundle_sha256", sa.String(64), nullable=False), sa.Column("schema_sha256", sa.String(64), nullable=False), sa.Column("bundle_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "bundle_id", "bundle_sha256", name="uq_artifact_rule_tenant_digest"))
    _create("artifact_database_snapshots", sa.Column("database_id", sa.String(100), nullable=False), sa.Column("database_kind", sa.String(32), nullable=False), sa.Column("database_version", sa.String(64), nullable=False), sa.Column("database_sha256", sa.String(64), nullable=False), sa.Column("schema_sha256", sa.String(64), nullable=False), sa.Column("database_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "database_id", "database_sha256", name="uq_artifact_database_tenant_digest"))
    _create("artifact_bindings", sa.Column("binding_id", sa.String(100), nullable=False), sa.Column("artifact_kind", sa.String(32), nullable=False), sa.Column("artifact_sha256", sa.String(64), nullable=False), sa.Column("manifest_sha256", sa.String(64), nullable=False), sa.Column("declared_files", sa.Integer(), nullable=False), sa.Column("declared_bytes", sa.BigInteger(), nullable=False), sa.Column("classification", sa.String(32), nullable=False), sa.Column("binding_state", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "binding_id", name="uq_artifact_binding_tenant_id"))
    _create("artifact_analysis_plans", sa.Column("plan_id", sa.String(100), nullable=False), sa.Column("profile_record_id", sa.String(64), sa.ForeignKey("artifact_pipeline_profiles.id"), nullable=False), sa.Column("binding_record_id", sa.String(64), sa.ForeignKey("artifact_bindings.id"), nullable=False), sa.Column("rule_bundle_id", sa.String(64), sa.ForeignKey("artifact_rule_bundles.id"), nullable=False), sa.Column("database_snapshot_id", sa.String(64), sa.ForeignKey("artifact_database_snapshots.id"), nullable=False), sa.Column("policy_decision_id", sa.String(100), nullable=False), sa.Column("reservation_id", sa.String(100), nullable=False), sa.Column("artifact_lease_id", sa.String(100), nullable=False), sa.Column("plan_sha256", sa.String(64), nullable=False), sa.Column("plan_state", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "plan_id", name="uq_artifact_plan_tenant_id"))
    _create("artifact_analysis_runs", sa.Column("run_id", sa.String(100), nullable=False), sa.Column("plan_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_plans.id"), nullable=False), sa.Column("job_id", sa.String(100), nullable=False), sa.Column("runner_id", sa.String(100), nullable=False), sa.Column("run_state", sa.String(32), nullable=False), sa.Column("complete", sa.Boolean(), nullable=False), sa.Column("partial_reasons", sa.JSON(), nullable=False), sa.Column("result_sha256", sa.String(64)), sa.Column("untrusted_execution_count", sa.Integer(), nullable=False), sa.UniqueConstraint("tenant_id", "run_id", name="uq_artifact_run_tenant_id"))
    _create("artifact_manifest_entries", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("path", sa.String(500), nullable=False), sa.Column("entry_kind", sa.String(32), nullable=False), sa.Column("size_bytes", sa.BigInteger(), nullable=False), sa.Column("entry_sha256", sa.String(64), nullable=False), sa.Column("compressed_bytes", sa.BigInteger(), nullable=False), sa.UniqueConstraint("tenant_id", "run_record_id", "path", name="uq_artifact_entry_tenant_run_path"))
    _create("artifact_components", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("component_id", sa.String(100), nullable=False), sa.Column("purl", sa.String(500)), sa.Column("component_type", sa.String(64), nullable=False), sa.Column("name", sa.String(300), nullable=False), sa.Column("component_version", sa.String(200)), sa.Column("component_sha256", sa.String(64), nullable=False), sa.Column("identity_complete", sa.Boolean(), nullable=False), sa.UniqueConstraint("tenant_id", "run_record_id", "component_id", name="uq_artifact_component_tenant_run"))
    _create("artifact_license_observations", sa.Column("observation_id", sa.String(100), nullable=False), sa.Column("component_record_id", sa.String(64), sa.ForeignKey("artifact_components.id"), nullable=False), sa.Column("license_expression", sa.String(500), nullable=False), sa.Column("license_state", sa.String(32), nullable=False), sa.Column("rule_sha256", sa.String(64), nullable=False), sa.UniqueConstraint("tenant_id", "observation_id", name="uq_artifact_license_tenant_id"))
    _create("artifact_vulnerability_observations", sa.Column("observation_id", sa.String(100), nullable=False), sa.Column("component_record_id", sa.String(64), sa.ForeignKey("artifact_components.id"), nullable=False), sa.Column("advisory_id", sa.String(100), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("database_sha256", sa.String(64), nullable=False), sa.Column("observation_sha256", sa.String(64), nullable=False), sa.Column("evidence_instance_id", sa.String(100)), sa.UniqueConstraint("tenant_id", "observation_id", name="uq_artifact_vulnerability_tenant_id"))
    _create("artifact_vex_annotations", sa.Column("annotation_id", sa.String(100), nullable=False), sa.Column("observation_record_id", sa.String(64), sa.ForeignKey("artifact_vulnerability_observations.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("justification", sa.Text(), nullable=False), sa.Column("requested_by", sa.String(64), nullable=False), sa.Column("approved_by", sa.String(64), nullable=False), sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("supersedes_annotation_id", sa.String(100)), sa.UniqueConstraint("tenant_id", "annotation_id", name="uq_artifact_vex_tenant_id"))
    _create("artifact_credential_findings", sa.Column("finding_id", sa.String(100), nullable=False), sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("path", sa.String(500), nullable=False), sa.Column("line", sa.Integer(), nullable=False), sa.Column("rule_id", sa.String(100), nullable=False), sa.Column("classification", sa.String(64), nullable=False), sa.Column("redacted_fragment", sa.String(32), nullable=False), sa.Column("evidence_instance_id", sa.String(100)), sa.UniqueConstraint("tenant_id", "run_record_id", "fingerprint", name="uq_artifact_credential_tenant_fingerprint"))
    _create("artifact_static_findings", sa.Column("finding_id", sa.String(100), nullable=False), sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("stage_kind", sa.String(32), nullable=False), sa.Column("rule_id", sa.String(100), nullable=False), sa.Column("resource_id", sa.String(500), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("finding_sha256", sa.String(64), nullable=False), sa.Column("evidence_instance_id", sa.String(100)), sa.UniqueConstraint("tenant_id", "finding_id", name="uq_artifact_static_finding_tenant_id"))
    _create("artifact_mobile_observations", sa.Column("observation_id", sa.String(100), nullable=False), sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("platform", sa.String(32), nullable=False), sa.Column("control_id", sa.String(100), nullable=False), sa.Column("resource_id", sa.String(500), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("observation_sha256", sa.String(64), nullable=False), sa.UniqueConstraint("tenant_id", "observation_id", name="uq_artifact_mobile_tenant_id"))
    _create("artifact_cleanup_receipts", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("artifact_analysis_runs.id"), nullable=False), sa.Column("receipt_id", sa.String(100), nullable=False), sa.Column("lease_revoked", sa.Boolean(), nullable=False), sa.Column("new_reads_blocked", sa.Boolean(), nullable=False), sa.Column("untrusted_execution_count", sa.Integer(), nullable=False), sa.Column("residual_resource_count", sa.Integer(), nullable=False), sa.Column("inventory_sha256", sa.String(64), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "receipt_id", name="uq_artifact_cleanup_tenant_id"))
    for table in TABLES: _tenant_rls(table)


def downgrade() -> None:
    for table in reversed(TABLES): op.execute(f'DROP TABLE IF EXISTS "{table}"')


def _create(name: str, *columns: object) -> None:
    op.create_table(name, sa.Column("id", sa.String(64), primary_key=True), *columns, *_owned())


def _owned() -> tuple[sa.Column, ...]:
    return (sa.Column("tenant_id", sa.String(64), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))


def _tenant_rls(table: str) -> None:
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'); op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(f'CREATE POLICY "{table}_tenant_isolation" ON "{table}" USING (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\')) WITH CHECK (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\'))')
