"""compat_112 consent-driven sink-only email and canary simulation."""

from alembic import op
import sqlalchemy as sa


revision = "0019_r112_human"
down_revision = "0018_r111_purple"
branch_labels = None
depends_on = None


TABLES = (
    "human_adapter_artifacts", "human_campaign_manifests", "human_consent_rosters", "human_suppression_lists",
    "human_privacy_reviews", "human_message_templates", "human_campaign_approvals", "human_campaign_plans",
    "human_campaign_runs", "human_delivery_receipts", "human_minimized_events", "human_canary_correlations",
    "human_stop_receipts", "human_deletion_receipts", "human_rehearsal_receipts", "human_evidence_records",
)


def upgrade() -> None:
    _create("human_adapter_artifacts", sa.Column("adapter_id", sa.String(100), nullable=False), sa.Column("adapter_sha256", sa.String(64), nullable=False), sa.Column("owned", sa.Boolean(), nullable=False), sa.Column("external_delivery_allowed", sa.Boolean(), nullable=False), sa.Column("adapter_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "adapter_id", "adapter_sha256", name="uq_human_adapter_tenant_digest"))
    _create("human_campaign_manifests", sa.Column("campaign_id", sa.String(100), nullable=False), sa.Column("campaign_sha256", sa.String(64), nullable=False), sa.Column("purpose", sa.String(200), nullable=False), sa.Column("jurisdiction_review_id", sa.String(100), nullable=False), sa.Column("privacy_review_id", sa.String(100), nullable=False), sa.Column("roster_sha256", sa.String(64), nullable=False), sa.Column("suppression_sha256", sa.String(64), nullable=False), sa.Column("template_sha256", sa.String(64), nullable=False), sa.Column("sink_id", sa.String(100), nullable=False), sa.Column("canary_id", sa.String(100), nullable=False), sa.Column("max_deliveries", sa.Integer(), nullable=False), sa.Column("rate_per_minute", sa.Integer(), nullable=False), sa.Column("retention_seconds", sa.Integer(), nullable=False), sa.Column("human_delivery", sa.Boolean(), nullable=False), sa.Column("external_delivery", sa.Boolean(), nullable=False), sa.Column("manifest_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "campaign_id", "campaign_sha256", name="uq_human_campaign_tenant_digest"))
    _create("human_consent_rosters", sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("roster_id", sa.String(100), nullable=False), sa.Column("roster_sha256", sa.String(64), nullable=False), sa.Column("recipient_count", sa.Integer(), nullable=False), sa.Column("synthetic_only", sa.Boolean(), nullable=False), sa.Column("consent_state", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "roster_id", "roster_sha256", name="uq_human_roster_tenant_digest"))
    _create("human_suppression_lists", sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("suppression_id", sa.String(100), nullable=False), sa.Column("suppression_sha256", sa.String(64), nullable=False), sa.Column("deny_real_recipients", sa.Boolean(), nullable=False), sa.Column("suppression_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "suppression_id", "suppression_sha256", name="uq_human_suppression_tenant_digest"))
    _create("human_privacy_reviews", sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("review_id", sa.String(100), nullable=False), sa.Column("purpose", sa.String(200), nullable=False), sa.Column("jurisdiction", sa.String(64), nullable=False), sa.Column("minimized_categories", sa.JSON(), nullable=False), sa.Column("retention_seconds", sa.Integer(), nullable=False), sa.Column("deletion_required", sa.Boolean(), nullable=False), sa.Column("reviewed_by", sa.String(64), nullable=False), sa.Column("review_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "review_id", name="uq_human_privacy_tenant_id"))
    _create("human_message_templates", sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("template_id", sa.String(100), nullable=False), sa.Column("template_sha256", sa.String(64), nullable=False), sa.Column("rendered_sha256", sa.String(64), nullable=False), sa.Column("external_link_count", sa.Integer(), nullable=False), sa.Column("attachment_count", sa.Integer(), nullable=False), sa.Column("tracking_count", sa.Integer(), nullable=False), sa.Column("template_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "template_id", "template_sha256", name="uq_human_template_tenant_digest"))
    _create("human_campaign_approvals", sa.Column("approval_id", sa.String(100), nullable=False), sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("campaign_sha256", sa.String(64), nullable=False), sa.Column("rendered_sha256", sa.String(64), nullable=False), sa.Column("test_delivery_sha256", sa.String(64), nullable=False), sa.Column("requester_id", sa.String(64), nullable=False), sa.Column("preview_reviewer_id", sa.String(64), nullable=False), sa.Column("send_approver_id", sa.String(64), nullable=False), sa.Column("approval_state", sa.String(32), nullable=False), sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "approval_id", name="uq_human_approval_tenant_id"))
    _create("human_campaign_plans", sa.Column("plan_id", sa.String(100), nullable=False), sa.Column("campaign_record_id", sa.String(64), sa.ForeignKey("human_campaign_manifests.id"), nullable=False), sa.Column("approval_record_id", sa.String(64), sa.ForeignKey("human_campaign_approvals.id"), nullable=False), sa.Column("policy_decision_id", sa.String(100), nullable=False), sa.Column("roe_revision", sa.String(100), nullable=False), sa.Column("reservation_id", sa.String(100), nullable=False), sa.Column("delivery_lease_id", sa.String(100), nullable=False), sa.Column("stop_switch_id", sa.String(100), nullable=False), sa.Column("quota_id", sa.String(100), nullable=False), sa.Column("plan_sha256", sa.String(64), nullable=False), sa.Column("plan_state", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "plan_id", name="uq_human_plan_tenant_id"))
    _create("human_campaign_runs", sa.Column("run_id", sa.String(100), nullable=False), sa.Column("plan_record_id", sa.String(64), sa.ForeignKey("human_campaign_plans.id"), nullable=False), sa.Column("job_id", sa.String(100), nullable=False), sa.Column("runner_id", sa.String(100), nullable=False), sa.Column("run_state", sa.String(32), nullable=False), sa.Column("new_delivery_blocked", sa.Boolean(), nullable=False), sa.Column("human_delivery_count", sa.Integer(), nullable=False), sa.Column("external_delivery_count", sa.Integer(), nullable=False), sa.Column("deletion_verified", sa.Boolean(), nullable=False), sa.Column("failure_code", sa.String(100)), sa.UniqueConstraint("tenant_id", "run_id", name="uq_human_run_tenant_id"))
    _create("human_delivery_receipts", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("receipt_id", sa.String(100), nullable=False), sa.Column("message_id", sa.String(100), nullable=False), sa.Column("message_sha256", sa.String(64), nullable=False), sa.Column("sink_id", sa.String(100), nullable=False), sa.Column("captured", sa.Boolean(), nullable=False), sa.Column("human_delivered", sa.Boolean(), nullable=False), sa.Column("external_contact_count", sa.Integer(), nullable=False), sa.Column("relay_count", sa.Integer(), nullable=False), sa.Column("forward_count", sa.Integer(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "receipt_id", name="uq_human_delivery_tenant_id"))
    _create("human_minimized_events", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("event_id", sa.String(100), nullable=False), sa.Column("message_id", sa.String(100), nullable=False), sa.Column("event_category", sa.String(64), nullable=False), sa.Column("body_sha256", sa.String(64), nullable=False), sa.Column("signature_verified", sa.Boolean(), nullable=False), sa.Column("replay_checked", sa.Boolean(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "event_id", name="uq_human_event_tenant_id"))
    _create("human_canary_correlations", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("canary_id", sa.String(100), nullable=False), sa.Column("message_id", sa.String(100), nullable=False), sa.Column("sink_id", sa.String(100), nullable=False), sa.Column("correlation_sha256", sa.String(64), nullable=False), sa.Column("triggered", sa.Boolean(), nullable=False), sa.Column("triggered_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "run_record_id", "canary_id", name="uq_human_canary_tenant_run"))
    _create("human_stop_receipts", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("receipt_id", sa.String(100), nullable=False), sa.Column("new_delivery_blocked", sa.Boolean(), nullable=False), sa.Column("delivery_lease_revoked", sa.Boolean(), nullable=False), sa.Column("recall_claimed", sa.Boolean(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "receipt_id", name="uq_human_stop_tenant_id"))
    _create("human_deletion_receipts", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("receipt_id", sa.String(100), nullable=False), sa.Column("deleted_message_count", sa.Integer(), nullable=False), sa.Column("deleted_event_count", sa.Integer(), nullable=False), sa.Column("deleted_canary_count", sa.Integer(), nullable=False), sa.Column("residual_count", sa.Integer(), nullable=False), sa.Column("zero_residual", sa.Boolean(), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "receipt_id", name="uq_human_deletion_tenant_id"))
    _create("human_rehearsal_receipts", sa.Column("rehearsal_id", sa.String(100), nullable=False), sa.Column("campaign_sha256", sa.String(64), nullable=False), sa.Column("plan_sha256", sa.String(64), nullable=False), sa.Column("delivery_sha256", sa.String(64), nullable=False), sa.Column("event_sha256", sa.String(64), nullable=False), sa.Column("deletion_sha256", sa.String(64), nullable=False), sa.Column("human_delivery_count", sa.Integer(), nullable=False), sa.Column("external_contact_count", sa.Integer(), nullable=False), sa.Column("residual_count", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "rehearsal_id", name="uq_human_rehearsal_tenant_id"))
    _create("human_evidence_records", sa.Column("run_record_id", sa.String(64), sa.ForeignKey("human_campaign_runs.id"), nullable=False), sa.Column("evidence_id", sa.String(100), nullable=False), sa.Column("evidence_kind", sa.String(64), nullable=False), sa.Column("evidence_sha256", sa.String(64), nullable=False), sa.Column("redaction_state", sa.String(32), nullable=False), sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "evidence_id", name="uq_human_evidence_tenant_id"))
    for table in TABLES:
        _tenant_rls(table)


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f'DROP TABLE IF EXISTS "{table}"')


def _create(name: str, *columns: object) -> None:
    op.create_table(name, sa.Column("id", sa.String(64), primary_key=True), *columns, *_owned())


def _owned() -> tuple[sa.Column, ...]:
    return (sa.Column("tenant_id", sa.String(64), nullable=False), sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))


def _tenant_rls(table: str) -> None:
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(f'CREATE POLICY "{table}_tenant_isolation" ON "{table}" USING (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\')) WITH CHECK (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\'))')
