"""compat_115 finding, remediation, report, and fixture-connector operations."""

from alembic import op
import sqlalchemy as sa


revision = "0022_r115_findings"
down_revision = "0021_r114_mcp"
branch_labels = None
depends_on = None

TABLES = (
    "finding_import_sessions", "finding_import_records", "managed_issues", "finding_occurrences",
    "finding_evidence_links", "finding_operations", "finding_comments", "finding_risk_acceptances",
    "finding_retests", "finding_report_snapshots", "finding_report_claims", "finding_publications",
    "finding_connector_profiles", "finding_connector_deliveries", "finding_connector_attempts",
    "finding_connector_callbacks", "finding_connector_reconciliations",
)


def upgrade() -> None:
    _create("finding_import_sessions", sa.Column("import_id", sa.String(100), nullable=False), sa.Column("adapter_id", sa.String(100), nullable=False), sa.Column("run_id", sa.String(100), nullable=False), sa.Column("baseline_run_id", sa.String(100)), sa.Column("coverage_state", sa.String(32), nullable=False), sa.Column("recipe_version", sa.String(64), nullable=False), sa.Column("import_sha256", sa.String(64), nullable=False), sa.Column("record_count", sa.Integer(), nullable=False), sa.Column("import_state", sa.String(32), nullable=False), sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "import_id", name="uq_finding_import_tenant_id"))
    _create("finding_import_records", sa.Column("import_record_id", sa.String(100), nullable=False), sa.Column("import_record_ref", sa.String(64), sa.ForeignKey("finding_import_sessions.id"), nullable=False), sa.Column("source_record_id", sa.String(100), nullable=False), sa.Column("source_record_sha256", sa.String(64), nullable=False), sa.Column("issue_fingerprint", sa.String(64), nullable=False), sa.Column("candidate_sha256", sa.String(64), nullable=False), sa.Column("reason_codes_sha256", sa.String(64), nullable=False), sa.Column("correlation_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "import_record_ref", "source_record_id", name="uq_finding_import_record_tenant_source"))
    _create("managed_issues", sa.Column("issue_id", sa.String(100), nullable=False), sa.Column("issue_fingerprint", sa.String(64), nullable=False), sa.Column("fingerprint_recipe", sa.String(64), nullable=False), sa.Column("title", sa.String(500), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("confidence", sa.String(32), nullable=False), sa.Column("taxonomy_sha256", sa.String(64), nullable=False), sa.Column("controls_sha256", sa.String(64), nullable=False), sa.Column("disposition", sa.String(32), nullable=False), sa.Column("disposition_revision", sa.Integer(), nullable=False), sa.Column("owner_id", sa.String(64)), sa.Column("sla_due_at", sa.DateTime(timezone=True)), sa.Column("remediation_sha256", sa.String(64), nullable=False), sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False), sa.Column("issue_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "issue_id", name="uq_managed_issue_tenant_id"), sa.UniqueConstraint("tenant_id", "issue_fingerprint", name="uq_managed_issue_tenant_fingerprint"))
    _create("finding_occurrences", sa.Column("occurrence_id", sa.String(100), nullable=False), sa.Column("issue_record_id", sa.String(64), sa.ForeignKey("managed_issues.id"), nullable=False), sa.Column("import_record_ref", sa.String(64), sa.ForeignKey("finding_import_records.id"), nullable=False), sa.Column("resource_sha256", sa.String(64), nullable=False), sa.Column("location_sha256", sa.String(64), nullable=False), sa.Column("tool_id", sa.String(100), nullable=False), sa.Column("tool_version", sa.String(100), nullable=False), sa.Column("rule_id", sa.String(200), nullable=False), sa.Column("rule_version", sa.String(100), nullable=False), sa.Column("database_version", sa.String(100), nullable=False), sa.Column("coverage_state", sa.String(32), nullable=False), sa.Column("occurrence_state", sa.String(32), nullable=False), sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "occurrence_id", name="uq_finding_occurrence_tenant_id"))
    _create("finding_evidence_links", sa.Column("evidence_link_id", sa.String(100), nullable=False), sa.Column("occurrence_record_id", sa.String(64), sa.ForeignKey("finding_occurrences.id"), nullable=False), sa.Column("evidence_id", sa.String(100), nullable=False), sa.Column("evidence_sha256", sa.String(64), nullable=False), sa.Column("redaction_state", sa.String(32), nullable=False), sa.Column("purpose", sa.String(32), nullable=False), sa.Column("link_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "evidence_link_id", name="uq_finding_evidence_link_tenant_id"))
    _create("finding_operations", sa.Column("operation_id", sa.String(100), nullable=False), sa.Column("issue_record_id", sa.String(64), sa.ForeignKey("managed_issues.id"), nullable=False), sa.Column("operation_kind", sa.String(64), nullable=False), sa.Column("actor_id", sa.String(64), nullable=False), sa.Column("from_state", sa.String(32), nullable=False), sa.Column("to_state", sa.String(32), nullable=False), sa.Column("operation_sha256", sa.String(64), nullable=False), sa.Column("predecessor_sha256", sa.String(64), nullable=False), sa.Column("successor_sha256", sa.String(64), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "operation_id", name="uq_finding_operation_tenant_id"))
    _create("finding_comments", sa.Column("comment_id", sa.String(100), nullable=False), sa.Column("issue_record_id", sa.String(64), sa.ForeignKey("managed_issues.id"), nullable=False), sa.Column("author_id", sa.String(64), nullable=False), sa.Column("comment_sha256", sa.String(64), nullable=False), sa.Column("visibility", sa.String(32), nullable=False), sa.Column("comment_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "comment_id", name="uq_finding_comment_tenant_id"))
    _create("finding_risk_acceptances", sa.Column("acceptance_id", sa.String(100), nullable=False), sa.Column("issue_record_id", sa.String(64), sa.ForeignKey("managed_issues.id"), nullable=False), sa.Column("approver_id", sa.String(64), nullable=False), sa.Column("rationale_sha256", sa.String(64), nullable=False), sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acceptance_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "acceptance_id", name="uq_finding_acceptance_tenant_id"))
    _create("finding_retests", sa.Column("retest_id", sa.String(100), nullable=False), sa.Column("issue_record_id", sa.String(64), sa.ForeignKey("managed_issues.id"), nullable=False), sa.Column("baseline_run_id", sa.String(100), nullable=False), sa.Column("retest_run_id", sa.String(100)), sa.Column("coverage_state", sa.String(32), nullable=False), sa.Column("result_state", sa.String(32), nullable=False), sa.Column("requested_by", sa.String(64), nullable=False), sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "retest_id", name="uq_finding_retest_tenant_id"))
    _create("finding_report_snapshots", sa.Column("report_id", sa.String(100), nullable=False), sa.Column("audience", sa.String(32), nullable=False), sa.Column("reviewed_snapshot_sha256", sa.String(64), nullable=False), sa.Column("policy_revision", sa.String(100), nullable=False), sa.Column("roe_version_id", sa.String(100), nullable=False), sa.Column("coverage_state", sa.String(32), nullable=False), sa.Column("report_sha256", sa.String(64), nullable=False), sa.Column("generation_profile", sa.String(64), nullable=False), sa.Column("publication_block_sha256", sa.String(64), nullable=False), sa.Column("report_state", sa.String(32), nullable=False), sa.Column("generated_by", sa.String(64), nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "report_id", "report_sha256", name="uq_finding_report_tenant_digest"))
    _create("finding_report_claims", sa.Column("claim_id", sa.String(100), nullable=False), sa.Column("report_record_id", sa.String(64), sa.ForeignKey("finding_report_snapshots.id"), nullable=False), sa.Column("claim_sha256", sa.String(64), nullable=False), sa.Column("evidence_set_sha256", sa.String(64), nullable=False), sa.Column("provenance", sa.String(32), nullable=False), sa.Column("reviewer_adopted", sa.Boolean(), nullable=False), sa.Column("claim_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "claim_id", name="uq_finding_report_claim_tenant_id"))
    _create("finding_publications", sa.Column("publication_id", sa.String(100), nullable=False), sa.Column("report_record_id", sa.String(64), sa.ForeignKey("finding_report_snapshots.id"), nullable=False), sa.Column("report_sha256", sa.String(64), nullable=False), sa.Column("reviewer_id", sa.String(64), nullable=False), sa.Column("publisher_id", sa.String(64), nullable=False), sa.Column("publication_state", sa.String(32), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "publication_id", name="uq_finding_publication_tenant_id"))
    _create("finding_connector_profiles", sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("profile_revision", sa.Integer(), nullable=False), sa.Column("connector_kind", sa.String(32), nullable=False), sa.Column("destination_allowlist_sha256", sa.String(64), nullable=False), sa.Column("field_allowlist_sha256", sa.String(64), nullable=False), sa.Column("credential_reference_id", sa.String(100)), sa.Column("callback_key_reference_id", sa.String(100)), sa.Column("network_enabled", sa.Boolean(), nullable=False), sa.Column("profile_state", sa.String(32), nullable=False), sa.UniqueConstraint("tenant_id", "profile_id", "profile_revision", name="uq_finding_connector_profile_tenant_revision"))
    _create("finding_connector_deliveries", sa.Column("delivery_id", sa.String(100), nullable=False), sa.Column("profile_record_id", sa.String(64), sa.ForeignKey("finding_connector_profiles.id"), nullable=False), sa.Column("report_record_id", sa.String(64), sa.ForeignKey("finding_report_snapshots.id"), nullable=False), sa.Column("snapshot_sha256", sa.String(64), nullable=False), sa.Column("destination_key_sha256", sa.String(64), nullable=False), sa.Column("fields_sha256", sa.String(64), nullable=False), sa.Column("idempotency_key", sa.String(200), nullable=False), sa.Column("delivery_state", sa.String(32), nullable=False), sa.Column("next_attempt_at", sa.DateTime(timezone=True)), sa.Column("attempt_count", sa.Integer(), nullable=False), sa.UniqueConstraint("tenant_id", "profile_record_id", "idempotency_key", name="uq_finding_connector_delivery_tenant_key"))
    _create("finding_connector_attempts", sa.Column("attempt_id", sa.String(100), nullable=False), sa.Column("delivery_record_id", sa.String(64), sa.ForeignKey("finding_connector_deliveries.id"), nullable=False), sa.Column("attempt_number", sa.Integer(), nullable=False), sa.Column("request_sha256", sa.String(64), nullable=False), sa.Column("response_sha256", sa.String(64)), sa.Column("reason_code", sa.String(100), nullable=False), sa.Column("attempt_state", sa.String(32), nullable=False), sa.Column("network_contact_count", sa.Integer(), nullable=False), sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "delivery_record_id", "attempt_number", name="uq_finding_connector_attempt_tenant_number"))
    _create("finding_connector_callbacks", sa.Column("callback_id", sa.String(100), nullable=False), sa.Column("delivery_record_id", sa.String(64), sa.ForeignKey("finding_connector_deliveries.id"), nullable=False), sa.Column("nonce_sha256", sa.String(64), nullable=False), sa.Column("envelope_sha256", sa.String(64), nullable=False), sa.Column("signature_sha256", sa.String(64), nullable=False), sa.Column("callback_state", sa.String(32), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "nonce_sha256", name="uq_finding_connector_callback_tenant_nonce"))
    _create("finding_connector_reconciliations", sa.Column("reconciliation_id", sa.String(100), nullable=False), sa.Column("delivery_record_id", sa.String(64), sa.ForeignKey("finding_connector_deliveries.id"), nullable=False), sa.Column("internal_state", sa.String(32), nullable=False), sa.Column("external_state", sa.String(32), nullable=False), sa.Column("external_object_sha256", sa.String(64), nullable=False), sa.Column("reconciliation_state", sa.String(32), nullable=False), sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "reconciliation_id", name="uq_finding_connector_reconciliation_tenant_id"))
    for table in TABLES:
        _tenant_rls(table)


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f'DROP TABLE IF EXISTS "{table}"')


def _create(name: str, *columns: object) -> None:
    op.create_table(name, sa.Column("id", sa.String(64), primary_key=True), *columns, *_owned())


def _owned() -> tuple[sa.Column, ...]:
    return (sa.Column("tenant_id", sa.String(64), nullable=False), sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))


def _tenant_rls(table: str) -> None:
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(f'CREATE POLICY "{table}_tenant_isolation" ON "{table}" USING (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\')) WITH CHECK (tenant_id = NULLIF(current_setting(\'redagent.tenant_id\', true), \'\'))')
