import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const root = process.cwd();
const contractCheck = spawnSync(
  process.execPath,
  [path.join(root, "scripts", "run_openapi_export.mjs"), "--check"],
  { cwd: root, stdio: "inherit", shell: false },
);
if (contractCheck.status !== 0) process.exit(contractCheck.status ?? 1);

const openapiPath = path.join(root, "frontend", "openapi.json");
const generatedPath = path.join(root, "frontend", "src", "generated", "api.d.ts");
const ast = await openapiTS(pathToFileURL(openapiPath));
const banner = "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";
const expected = `${banner}${astToString(ast)}`;
const current = await readFile(generatedPath, "utf8");
if (current !== expected) {
  process.stderr.write("generated_api_types_drift_detected\n");
  process.exit(1);
}
process.stdout.write("generated_api_contract_current\n");
